In [2]:
import numpy as np

import matplotlib.pyplot as plt

import pandas as pd

from pandas import Series, DataFrame

import random

A Series is a one-dimensional array-like object containing a sequence of
 values (of similar types to NumPy types) and an associated array of data
 labels, called its index.

In [8]:
obj = pd.Series([4, 7, -5, 3]) # String representation 

obj

0    4
1    7
2   -5
3    3
dtype: int64

In [9]:
obj.values # Array representation

array([ 4,  7, -5,  3])

In [7]:
obj.index # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [11]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

obj2

d    4
b    7
a   -5
c    3
dtype: int64

 Here ['c', 'a', 'd'] is interpreted as a list of indices, even though it
 contains strings instead of integers.

In [12]:
obj2["a"]

np.int64(-5)

In [13]:
obj2["d"] = 1000

In [16]:
obj2[["c", "a", "d"]]

c       3
a      -5
d    1000
dtype: int64

In [17]:
obj2[obj2 > 2]

d    1000
b       7
c       3
dtype: int64

In [18]:
obj2 * 2

d    2000
b      14
a     -10
c       6
dtype: int64

In [24]:
np.exp(obj2)

c:\Users\pc\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)

d            inf
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

Another way to think about a Series is as a fixed-length, ordered dict, as it
 is a mapping of index values to data values. It can be used in many contexts
 where you might use a dict:

In [25]:
"b" in obj2

True

In [26]:
"e" in obj2

False

 Should you have data contained in a Python dict, you can create a Series
 from it by passing the dict:

In [27]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [28]:
obj3 = pd.Series(sdata)

obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [30]:
# Passing the dict keys in the order you want them to appear in
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [31]:
obj4 = pd.Series(sdata, index=states)

obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [32]:
pd.isnull(obj4) #  Detect missing data

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [33]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [34]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [35]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [36]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [37]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Both the Series object itself and its index have a name attribute, which
 integrates with other key areas of pandas functionality:

In [38]:
obj4.name = "population"

In [39]:
obj4.index.name = "state"

In [40]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [41]:
obj # A Series’s index can be altered in-place by assignment

0    4
1    7
2   -5
3    3
dtype: int64

In [42]:
obj.index = ["Bob", 'Steve', 'Jeff', 'Ryan']

obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

A DataFrame represents a rectangular table of data and contains an ordered
 collection of columns, each of which can be a different value type (numeric,
 string, boolean, etc.). 
 
 The DataFrame has both a row and column index; it
 can be thought of as a dict of Series all sharing the same index. 
 
 Under the
 hood, the data is stored as one or more two-dimensional blocks rather than a
 list, dict, or some other collection of one-dimensional arrays.

 There are many ways to construct a DataFrame, though one of the most
 common is from a dict of equal-length lists or NumPy arrays:

In [19]:
data = {"state": ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
        }

In [45]:
frame = pd.DataFrame(data)

frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [46]:
#  For large DataFrames, the head method selects only the first five rows:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [48]:
# Specify a sequence of columns
pd.DataFrame(data, columns=["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [20]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                            index=["one", 'two', 'three', 'four', 'five', 'six'])

frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [50]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

A column in a DataFrame can be retrieved as a Series either by dict-like
 notation or by attribute:

In [51]:
frame2["state"]

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: str

In [52]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [53]:
#  Rows can also be retrieved by position or name with the special loc attribute.
frame2.loc["three"]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [54]:
frame2["debt"] = 1.5

frame2

       year   state  pop  debt
one    2000    Ohio  1.5   1.5
two    2001    Ohio  1.7   1.5
three  2002    Ohio  3.6   1.5
four   2001  Nevada  2.4   1.5
five   2002  Nevada  2.9   1.5
six    2003  Nevada  3.2   1.5

In [58]:
frame2["debt"] = np.arange(6.)

frame2

       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

If you assign a Series, its labels will be
 realigned exactly to the DataFrame’s index, inserting missing values in any
 holes:

In [62]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

In [63]:
frame2["debt"] = val

frame2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

 Assigning a column that doesn’t exist will create a new column. The del
 keyword will delete columns as with a dict.

 CAUTION: New columns should not be created with the frame2.eastern syntax.
 Dot notation is mainly for accessing existing columns.

In [21]:
frame2["eastern"] = frame2.state == "Ohio"

frame2

       year   state  pop debt  eastern
one    2000    Ohio  1.5  NaN     True
two    2001    Ohio  1.7  NaN     True
three  2002    Ohio  3.6  NaN     True
four   2001  Nevada  2.4  NaN    False
five   2002  Nevada  2.9  NaN    False
six    2003  Nevada  3.2  NaN    False

In [65]:
del frame2["eastern"]

In [66]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

 The column returned from indexing a DataFrame is a view on the underlying data, not a
 copy. 
 
 Thus, any in-place modifications to the Series will be reflected in the DataFrame.
 
 The column can be explicitly copied with the Series’s copy method.

Another common form of data is a nested dict of dicts:

In [3]:
pop = {"Nevada" : {2001: 2.4, 2002: 2.9},
        "Ohio" : {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [4]:
frame3 = pd.DataFrame(pop)

frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [5]:
frame3.sort_index()

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [6]:
frame3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [7]:
pd.DataFrame(pop, index=[2000, 2001, 2002])

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [11]:
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

The keys in the inner dicts are combined and sorted to form the index in the
 result:

In [9]:
pdata = {"Ohio": frame3["Ohio"][:-1],
         "Nevada": frame3["Nevada"][:2]}

In [10]:
pd,DataFrame(pdata)

(<module 'pandas' from 'c:\\Users\\pc\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pandas\\__init__.py'>,
       Ohio  Nevada
 2001   1.7     2.4
 2002   3.6     2.9)

In [12]:
frame3.index.name = "year"; frame3.columns.name = "state"

frame3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [13]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [22]:
frame2.values

array([[2000, 'Ohio', 1.5, nan, True],
       [2001, 'Ohio', 1.7, nan, True],
       [2002, 'Ohio', 3.6, nan, True],
       [2001, 'Nevada', 2.4, nan, False],
       [2002, 'Nevada', 2.9, nan, False],
       [2003, 'Nevada', 3.2, nan, False]], dtype=object)

 pandas’s Index objects are responsible for holding the axis labels and other
 metadata (like the axis name or names). 
 
 Any array or other sequence of
 labels you use when constructing a Series or DataFrame is internally
 converted to an Index:

In [3]:
obj = pd.Series(range(3), index=["a", "b", "c"])    # Index Objects

In [4]:
index = obj.index

In [5]:
index

Index(['a', 'b', 'c'], dtype='str')

In [6]:
index[1:]

Index(['b', 'c'], dtype='str')

Index objects are immutable and thus can’t be modified by the user:

In [7]:
index[1] = "d"

TypeError: Index does not support mutable operations

Immutability makes it safer to share Index objects among data structures:

In [8]:
labels = pd.Index(np.arange(3))

labels

Index([0, 1, 2], dtype='int64')

In [9]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [10]:
obj2.index is labels

True